### ISSUE TITLE
Tile files don't contain a mapping of potential targets to fibers.

### ISSUE THREAD

**Issue by weaverba137** [desihub/quicksurvey_example#9]
In HDU 2 of the tile files, potential targets are supposed to be listed.  However this appears only to be a list of targets, not a list of which *fibers* could have observed which targets.  I have heard that this HDU was supposed to contain "all TARGETIDs covered by *each* positioner, not the selected one" (emphasis mine).  This implies to me that for every *fiber* the HDU should contain the TARGETIDs that could have been observed *by that fiber*.

**Comment by forero** [comment]
The HDU 2 concatenates the TARGETIDs that could have been observed by all the fibers. Pages 4 and 5 of DocDB 1049 explains how to reconstruct the TARGETIDs that could have been observed by a single fiber.

**Comment by weaverba137** [comment]
OK, thanx, I see how that works.  However, while reading that document, I found a discrepancy:

> Let’s assume for simplicity that we have 4 fibers with IDs [0,1,2,3]. There
are in turn 4 different sets of targets that can be reached by each fiber. These
sets are [980,203], [736,102,304], [0] and [234] for fibers 0,1,2 and 3,
respectiveley. The index -1 for fiber 3 means that this fiber cannot reach any
target.

Where exactly is the index -1?  None of the target lists for the four fibers contain that number.

**Comment by forero** [comment]
You are right about the discrepancy in the documentation. The `[234]` should be instead `[-1]`. Thanks.
